kind: Deployment
apiVersion: apps/v1
metadata:
  name: caj-fare
  labels:
    app: caj-fare
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-fare
      version: v1
  template:
    metadata:
      labels:
        app: caj-fare
        version: v1
    spec:
      containers:
        - name: caj-fare
          image: 'quay.io/rhtw/caj-fare:2023-08-31-06-53-54'
          ports:
            - containerPort: 8080
              protocol: TCP
