kind: Deployment
apiVersion: apps/v1
metadata:
  name: caj-fare
  labels:
    app: caj-fare
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-fare
      version: v1
  template:
    metadata:
      labels:
        app: caj-fare
        version: v1
    spec:
      containers:
        - name: caj-fare
          image: 'quay.io/rhtw/caj-fare:2023-05-25-07-42-06'
          ports:
            - containerPort: 8080
              protocol: TCP
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: caj-fare
    version: v1
  name: caj-fare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-fare
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: caj-fare
        version: v1
    spec:
      containers:
      - image: 'quay.io/rhtw/caj-fare:2023-05-25-07-42-06'
        name: caj-fare
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
status: {}
